// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7VQUPsBkrw1xGbk7-gX4zlBNjOKhVwwk',
    appId: '1:75869516456:web:8674eb600daea4bf0c889d',
    messagingSenderId: '75869516456',
    projectId: 'education-app-e7ced',
    authDomain: 'education-app-e7ced.firebaseapp.com',
    storageBucket: 'education-app-e7ced.firebasestorage.app',
    measurementId: 'G-X01NR4RHCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoNXuOnhtgoHbARwMIv2YslwARfdUdHiQ',
    appId: '1:75869516456:android:ac54bc1fa45c32f50c889d',
    messagingSenderId: '75869516456',
    projectId: 'education-app-e7ced',
    storageBucket: 'education-app-e7ced.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeP60t5NioJab1yIZZE0BA4hdK-p8n-c4',
    appId: '1:75869516456:ios:bf885b8527a97ce50c889d',
    messagingSenderId: '75869516456',
    projectId: 'education-app-e7ced',
    storageBucket: 'education-app-e7ced.firebasestorage.app',
    iosBundleId: 'com.example.educationApp',
  );
}
